#!/usr/bin/env bash
set -euo pipefail

# Configure an IEEE-style clubroom NAT gateway.
# Supports Debian-like and Fedora-like systems using NetworkManager + dnsmasq + nftables.
# The script is intentionally interactive and backs up files before writing.

LAN_CIDR_DEFAULT="192.168.0.1/24"
LAN_IP_DEFAULT="192.168.0.1"
DHCP_START_DEFAULT="192.168.0.50"
DHCP_END_DEFAULT="192.168.0.150"
DHCP_LEASE_DEFAULT="12h"
DNS_SERVERS_DEFAULT="8.8.8.8,1.1.1.1"
ENABLE_QOS_DEFAULT="no"
QOS_IPS_DEFAULT="192.168.0.111 192.168.0.128"
ENABLE_APPLIANCE_POWER_DEFAULT="yes"
DISABLE_USB_AUTOSUSPEND_DEFAULT="yes"
BACKUP_DIR="/root/ieee-gateway-backup-$(date +%Y%m%d-%H%M%S)"

log() { printf '\n[%s] %s\n' "INFO" "$*"; }
warn() { printf '\n[%s] %s\n' "WARN" "$*" >&2; }
fatal() { printf '\n[%s] %s\n' "ERROR" "$*" >&2; exit 1; }

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    fatal "Run this script as root: sudo $0"
  fi
}

ask() {
  local prompt="$1"
  local default="${2:-}"
  local value
  if [[ -n "$default" ]]; then
    read -r -p "$prompt [$default]: " value
    printf '%s' "${value:-$default}"
  else
    read -r -p "$prompt: " value
    printf '%s' "$value"
  fi
}

confirm() {
  local prompt="$1"
  local default="${2:-no}"
  local suffix="[y/N]"
  [[ "$default" == "yes" ]] && suffix="[Y/n]"
  local answer
  read -r -p "$prompt $suffix: " answer
  answer="${answer:-$default}"
  case "${answer,,}" in
    y|yes) return 0 ;;
    n|no) return 1 ;;
    *) warn "Please answer yes or no."; confirm "$prompt" "$default" ;;
  esac
}

backup_file() {
  local path="$1"
  if [[ -e "$path" || -L "$path" ]]; then
    mkdir -p "$BACKUP_DIR$(dirname "$path")"
    cp -a "$path" "$BACKUP_DIR$path"
    log "Backed up $path to $BACKUP_DIR$path"
  fi
}

have_cmd() { command -v "$1" >/dev/null 2>&1; }

install_packages() {
  local packages=(NetworkManager dnsmasq nftables iproute iproute-tc)

  if have_cmd apt-get; then
    log "Detected apt-based system. Installing required packages."
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y network-manager dnsmasq nftables iproute2
    if ! have_cmd tc; then
      apt-get install -y iproute2 || true
    fi
  elif have_cmd dnf; then
    log "Detected dnf-based system. Installing required packages."
    dnf install -y NetworkManager dnsmasq nftables iproute iproute-tc
  else
    fatal "Unsupported package manager. Install NetworkManager, dnsmasq, nftables, iproute/tc manually, then rerun."
  fi
}

show_detected_state() {
  log "Detected network state"
  ip -br addr || true
  echo
  ip route || true
  echo
  nmcli device status || true
}

select_interface() {
  local role="$1"
  local value
  value="$(ask "Enter ${role} interface name")"
  [[ -n "$value" ]] || fatal "${role} interface cannot be empty"
  [[ -d "/sys/class/net/$value" ]] || fatal "Interface $value does not exist"
  printf '%s' "$value"
}

write_nm_lan_connection() {
  local lan_iface="$1"
  local lan_cidr="$2"
  local con_name="ieee-clubroom-lan"

  log "Configuring LAN interface $lan_iface with NetworkManager static address $lan_cidr"

  if nmcli -t -f NAME connection show | grep -Fxq "$con_name"; then
    nmcli connection modify "$con_name" \
      connection.interface-name "$lan_iface" \
      ipv4.method manual \
      ipv4.addresses "$lan_cidr" \
      ipv4.never-default yes \
      ipv4.ignore-auto-dns yes \
      ipv6.method ignore
  else
    nmcli connection add type ethernet ifname "$lan_iface" con-name "$con_name" \
      ipv4.method manual \
      ipv4.addresses "$lan_cidr" \
      ipv4.never-default yes \
      ipv4.ignore-auto-dns yes \
      ipv6.method ignore
  fi

  nmcli connection up "$con_name"
}

write_dnsmasq_config() {
  local wan_iface="$1"
  local lan_iface="$2"
  local dhcp_start="$3"
  local dhcp_end="$4"
  local lease_time="$5"
  local router_ip="$6"
  local dns_servers="$7"

  backup_file /etc/dnsmasq.d/ieee-clubroom.conf
  mkdir -p /etc/dnsmasq.d
  cat > /etc/dnsmasq.d/ieee-clubroom.conf <<EOF
# IEEE clubroom gateway DHCP/DNS config.
# Generated by host-config/gateway/configure-clubroom-gateway.sh

interface=${lan_iface}
except-interface=${wan_iface}
listen-address=${router_ip}
bind-interfaces

dhcp-range=${dhcp_start},${dhcp_end},${lease_time}
dhcp-option=3,${router_ip}
dhcp-option=6,${dns_servers}

# Add static reservations below as needed, for example:
# dhcp-host=aa:bb:cc:dd:ee:ff,192.168.0.10,printer,infinite
EOF

  if grep -qE '^[[:space:]]*conf-dir=/etc/dnsmasq.d' /etc/dnsmasq.conf 2>/dev/null; then
    log "dnsmasq.conf already includes /etc/dnsmasq.d"
  else
    warn "This distro's dnsmasq.conf may not include /etc/dnsmasq.d by default. Adding conf-dir include."
    backup_file /etc/dnsmasq.conf
    printf '\n# Include IEEE clubroom and other drop-in configs\nconf-dir=/etc/dnsmasq.d/,*.conf\n' >> /etc/dnsmasq.conf
  fi
}

write_sysctl() {
  backup_file /etc/sysctl.d/99-ieee-ipforward.conf
  cat > /etc/sysctl.d/99-ieee-ipforward.conf <<'EOF'
# Enable IPv4 forwarding for IEEE clubroom gateway.
net.ipv4.ip_forward=1
EOF
  sysctl --system >/dev/null
}

write_gateway_apply_script() {
  local wan_iface="$1"
  local lan_iface="$2"
  local enable_qos="$3"
  local qos_ips="$4"

  backup_file /usr/local/sbin/ieee-gateway-apply.sh
  cat > /usr/local/sbin/ieee-gateway-apply.sh <<EOF
#!/usr/bin/env bash
set -euo pipefail

WAN_IFACE="${wan_iface}"
LAN_IFACE="${lan_iface}"
ENABLE_QOS="${enable_qos}"
QOS_IPS="${qos_ips}"

nft delete table inet ieee_gateway 2>/dev/null || true
nft delete table ip ieee_gateway_nat 2>/dev/null || true
nft delete table ip ieee_gateway_mangle 2>/dev/null || true

nft add table inet ieee_gateway
nft 'add chain inet ieee_gateway forward { type filter hook forward priority filter; policy accept; }'
nft add rule inet ieee_gateway forward iifname "\$WAN_IFACE" oifname "\$LAN_IFACE" ct state related,established accept
nft add rule inet ieee_gateway forward iifname "\$LAN_IFACE" oifname "\$WAN_IFACE" accept

nft add table ip ieee_gateway_nat
nft 'add chain ip ieee_gateway_nat postrouting { type nat hook postrouting priority srcnat; policy accept; }'
nft add rule ip ieee_gateway_nat postrouting oifname "\$WAN_IFACE" masquerade

if [[ "\$ENABLE_QOS" == "yes" ]]; then
  nft add table ip ieee_gateway_mangle
  nft 'add chain ip ieee_gateway_mangle prerouting { type filter hook prerouting priority mangle; policy accept; }'
  for ip in \$QOS_IPS; do
    nft add rule ip ieee_gateway_mangle prerouting ip saddr "\$ip" meta mark set 10
  done

  if command -v tc >/dev/null 2>&1; then
    tc qdisc del dev "\$WAN_IFACE" root 2>/dev/null || true
    tc qdisc add dev "\$WAN_IFACE" root handle 1: prio
    tc filter add dev "\$WAN_IFACE" parent 1: protocol ip handle 10 fw flowid 1:1
  else
    echo "WARN: tc not found; QoS nft packet marks were added but traffic control queue was not configured" >&2
  fi
fi
EOF
  chmod 0755 /usr/local/sbin/ieee-gateway-apply.sh
}

write_systemd_service() {
  backup_file /etc/systemd/system/ieee-gateway.service
  cat > /etc/systemd/system/ieee-gateway.service <<'EOF'
[Unit]
Description=IEEE Clubroom NAT Gateway
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/ieee-gateway-apply.sh
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
}

configure_appliance_power() {
  log "Enabling gateway appliance power settings"
  log "Masking sleep/hibernate targets so the clubroom network stays online when no user is logged in."

  systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target

  backup_file /etc/systemd/logind.conf.d/99-ieee-gateway-appliance.conf
  mkdir -p /etc/systemd/logind.conf.d
  cat > /etc/systemd/logind.conf.d/99-ieee-gateway-appliance.conf <<'EOF'
# IEEE clubroom gateway appliance mode.
# Keep the PC awake so DHCP/NAT/Wi-Fi clients do not lose network access.
[Login]
HandleSuspendKey=ignore
HandleHibernateKey=ignore
HandleLidSwitch=ignore
HandleLidSwitchDocked=ignore
IdleAction=ignore
EOF

  if systemctl is-active --quiet systemd-logind 2>/dev/null; then
    systemctl try-reload-or-restart systemd-logind || warn "Could not reload/restart systemd-logind; reboot to apply logind idle settings."
  fi
}

configure_usb_autosuspend() {
  log "Disabling USB autosuspend for reliability"
  log "This helps prevent USB Ethernet adapters from being power-managed off while acting as the LAN interface."

  backup_file /etc/udev/rules.d/99-ieee-no-usb-autosuspend.rules
  mkdir -p /etc/udev/rules.d
  cat > /etc/udev/rules.d/99-ieee-no-usb-autosuspend.rules <<'EOF'
# Keep USB devices, including USB Ethernet adapters, out of autosuspend.
ACTION=="add", SUBSYSTEM=="usb", TEST=="power/control", ATTR{power/control}="on"
EOF

  udevadm control --reload || warn "Could not reload udev rules"
  udevadm trigger --subsystem-match=usb || warn "Could not immediately apply udev rule; reboot or replug USB Ethernet to apply."
}

main() {
  require_root

  cat <<'EOF'
IEEE Clubroom Gateway Configurator

This will configure this PC as a NAT gateway for a private clubroom LAN.
It may change:
  - NetworkManager connection for the LAN interface
  - /etc/dnsmasq.d/ieee-clubroom.conf
  - /etc/sysctl.d/99-ieee-ipforward.conf
  - /usr/local/sbin/ieee-gateway-apply.sh
  - /etc/systemd/system/ieee-gateway.service
  - active nftables rules in tables named ieee_gateway*
  - optional appliance power settings to prevent sleep/hibernate
  - optional udev rule to prevent USB Ethernet autosuspend

It will not intentionally modify university/uplink authentication settings.
EOF

  show_detected_state

  confirm "Continue?" "no" || fatal "Aborted."

  if confirm "Install required packages now?" "yes"; then
    install_packages
  fi

  if systemctl is-active --quiet firewalld 2>/dev/null; then
    warn "firewalld is active. This script adds dedicated nftables tables but does not rewrite existing firewalld policy."
    warn "On Fedora, firewalld policy may still affect forwarding. Verify client internet after setup."
    confirm "Continue while firewalld is active?" "no" || fatal "Aborted. Review firewalld policy first."
  fi

  show_detected_state

  WAN_IFACE="$(select_interface "WAN/university uplink")"
  LAN_IFACE="$(select_interface "LAN/USB Ethernet downstream")"
  [[ "$WAN_IFACE" != "$LAN_IFACE" ]] || fatal "WAN and LAN interfaces must be different"

  LAN_CIDR="$(ask "LAN CIDR/address" "$LAN_CIDR_DEFAULT")"
  LAN_IP="$(ask "LAN gateway IP for DHCP clients" "$LAN_IP_DEFAULT")"
  DHCP_START="$(ask "DHCP range start" "$DHCP_START_DEFAULT")"
  DHCP_END="$(ask "DHCP range end" "$DHCP_END_DEFAULT")"
  DHCP_LEASE="$(ask "DHCP lease time" "$DHCP_LEASE_DEFAULT")"
  DNS_SERVERS="$(ask "DNS servers to hand to clients, comma-separated" "$DNS_SERVERS_DEFAULT")"

  ENABLE_QOS="no"
  QOS_IPS=""
  if confirm "Enable legacy QoS priority for selected client IPs?" "$ENABLE_QOS_DEFAULT"; then
    ENABLE_QOS="yes"
    QOS_IPS="$(ask "QoS priority client IPs, space-separated" "$QOS_IPS_DEFAULT")"
  fi

  cat <<'EOF'

Gateway appliance reliability settings:
  This PC is network infrastructure. If it sleeps or hibernates, the clubroom
  loses DHCP, NAT, DNS, and internet access. The defaults therefore prevent
  system sleep/hibernate and disable USB autosuspend so the USB Ethernet LAN
  adapter is less likely to power down.
EOF

  ENABLE_APPLIANCE_POWER="no"
  if confirm "Enable gateway appliance power settings to prevent sleep/hibernate?" "$ENABLE_APPLIANCE_POWER_DEFAULT"; then
    ENABLE_APPLIANCE_POWER="yes"
  fi

  DISABLE_USB_AUTOSUSPEND="no"
  if confirm "Disable USB autosuspend for USB Ethernet reliability?" "$DISABLE_USB_AUTOSUSPEND_DEFAULT"; then
    DISABLE_USB_AUTOSUSPEND="yes"
  fi

  cat <<EOF

Planned configuration:
  WAN interface:       $WAN_IFACE
  LAN interface:       $LAN_IFACE
  LAN address:         $LAN_CIDR
  DHCP range:          $DHCP_START - $DHCP_END
  DHCP gateway:        $LAN_IP
  DHCP DNS servers:    $DNS_SERVERS
  QoS enabled:         $ENABLE_QOS
  QoS IPs:             $QOS_IPS
  Prevent sleep:       $ENABLE_APPLIANCE_POWER
  USB autosuspend off: $DISABLE_USB_AUTOSUSPEND
  Backup directory:    $BACKUP_DIR
EOF

  confirm "Apply this configuration?" "no" || fatal "Aborted before changes."

  mkdir -p "$BACKUP_DIR"

  systemctl enable --now NetworkManager
  write_nm_lan_connection "$LAN_IFACE" "$LAN_CIDR"
  write_dnsmasq_config "$WAN_IFACE" "$LAN_IFACE" "$DHCP_START" "$DHCP_END" "$DHCP_LEASE" "$LAN_IP" "$DNS_SERVERS"
  write_sysctl
  write_gateway_apply_script "$WAN_IFACE" "$LAN_IFACE" "$ENABLE_QOS" "$QOS_IPS"
  write_systemd_service
  if [[ "$ENABLE_APPLIANCE_POWER" == "yes" ]]; then
    configure_appliance_power
  fi
  if [[ "$DISABLE_USB_AUTOSUSPEND" == "yes" ]]; then
    configure_usb_autosuspend
  fi

  systemctl enable --now dnsmasq
  systemctl restart dnsmasq
  systemctl enable --now ieee-gateway.service
  systemctl restart ieee-gateway.service

  log "Verification output"
  ip -br addr || true
  echo
  ip route || true
  echo
  nmcli device status || true
  echo
  systemctl --no-pager status dnsmasq || true
  echo
  systemctl --no-pager status ieee-gateway || true
  echo
  nft list ruleset | sed -n '/ieee_gateway/,+60p' || true
  echo
  systemctl status sleep.target suspend.target hibernate.target hybrid-sleep.target --no-pager || true

  cat <<EOF

Done.

Next steps:
  1. Configure the TP-Link as AP/dumb switch mode.
  2. Disable DHCP on the TP-Link.
  3. Set TP-Link LAN IP to 192.168.0.2.
  4. Connect mini-PC LAN/USB Ethernet to a TP-Link LAN port.
  5. Connect a client to Wi-Fi and verify:
       IP:      192.168.0.x
       Gateway: $LAN_IP
       DNS:     $DNS_SERVERS
       Internet works

Backups were saved under:
  $BACKUP_DIR
EOF
}

main "$@"
